name: Test and Lint
on: [push, pull_request]
jobs:
  testANDlint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pylint
      - name: Test
        run: python -m pytest
      - name: Lint
        run: pylint .
